# GET http://localhost:8080/protected HTTP/1.1

POST http://localhost:8080/ping HTTP/1.1
content-type: application/json

{
    "usernames": "sample",
    "password": "Wed, 21 Oct 2015 18:27:50 GMT"
}
